---
name: PR Check

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: crc
          POSTGRES_USER: crc
          POSTGRES_PASSWORD: crc
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Migrate DB
      run: make run-migration
    - name: Check Build
      run: make build-all
    - name: Run Tests
      run: go test ./...
